Working with isolated scope
SvtlnR/videoplayerAngularJS pull request #1
Opened 2018-10-01 07:15 UTC by SvtlnR

@soul-wish

2018-10-03 12:14 UTC, soul-wish requested changes
Поправь, пожалуйста описанные моменты. А за пр – 👍

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.html
> +	<video class="videoplayer" src="{{videoSrc}}" width="{{videoWidth}}">
Если хотелось использовать фиксированную ширину, то лучше выставлять ширину для верхнего контейнера, а внутри полный responsive.

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.html
> +		<div class="playBtn" ng-click="playPause()">
Не нужно делать кнопки div-ами ;) Старайся использовать HTML теги по назначению.

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.html
> +			<i class="fas fa-pause" ng-show="!paused">
Эти две кнопки должны быть одной, с подстановкой необходимого класса с помощью директивы `ng-class`

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      var video = angular.element(element.children()[0]).children()[0];
Так тоже не нужно. Всегда устанавливай CSS классы всем необходимым элементам. И тут нужно было написать что-т типа: element.find('.videoplayer')

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
А ведь можно просто написать: if (scope.autoplay) {}. Результат будет тем же?

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +        console.log(scope.duration);
Все debug штуки обязательно убирай перед коммитом (для этого есть ESLint у тебя)

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      scope.stopV = function() {
Странное имя функции :)

2018-10-03 12:14 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      angular.element(video).on("timeupdate", function(event) {
вот тут ты почему-то использовала более правильный подход к получению ноды видео

2018-10-03 13:18 UTC, SvtlnR commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
Я сначала так и думала, но если так написать, то не работает аutoplay.

2018-10-03 13:53 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
Почему? Сможешь разобраться?

2018-10-03 13:55 UTC, soul-wish commented on videoplayer_plugin/videoplayer.html
> +			<i ng-class="paused? 'fas fa-play':'fas fa-pause'">
Класс `fas` общий. Его можно и нужно вынести из директивы ng-class

2018-10-03 13:56 UTC, SvtlnR commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
постараюсь

2018-10-03 13:56 UTC, SvtlnR commented on videoplayer_plugin/videoplayer.html
> +			<i ng-class="paused? 'fas fa-play':'fas fa-pause'">
поняла, сейчас исправлю, спасибо

2018-10-03 14:04 UTC, SvtlnR commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
Поняла. Не работает, потому что для атрибута autoplay установлено значение "", которое будет приведено к false,  и undefined в свою очередь тоже приводиться к false, поэтому  при такой записи мы не заходим в блок if

2018-10-03 14:24 UTC, soul-wish commented on videoplayer_plugin/videoplayer.js
> +      if (scope.autoplay !== undefined) {
А попробуй поискать как понять установлен ли атрибут в директиве AngularJS или отсутствует.

2018-10-08 13:30 UTC, soul-wish commented
Влей пожалуйста этот ПР, потому что смотреть второй очень неудобно.

2018-10-08 19:33 UTC, merged